# Generated by Django 5.1 on 2024-08-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='game_table',
        ),
        migrations.AlterModelTable(
            name='round',
            table='round_table',
        ),
    ]
