# Generated by Django 5.1 on 2024-08-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_table_alter_round_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
